on: push

env:
  python-version: "3.11.6"
  poetry-version: "1.5.1"

jobs:
  python-test:
    runs-on: ubuntu-latest
    name: Python Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: hello
        run: echo "hi"
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy
    needs: [python-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello
        run: echo "sup"
